name: Fetch deleted files

on: [push, pull_request, workflow_dispatch]

jobs:
  replace-secrets:
    name: Deleted file recovering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Recover + content show
        shell: bash
        run: |
          set -x
          filesha=$(git log -n 1 --pretty=format:%H -- lala2.yaml | tail -n1)
          git checkout "$filesha" -- lala2.yaml
          ls
          cat lala2.yaml
