name: Fetch deleted files

on: [push, pull_request, workflow_dispatch]

jobs:
  replace-secrets:
    name: Deleted file recovering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Recover + content show
        shell: bash
        run: |
          pwd
          ls
          filesha=$(git log -n 1 --pretty=format:%H -- lala1.yaml | tail -n1)
          git checkout "$filesha" -- lala1.yaml
          cat lala1.yaml
