name: Fetch deleted files

on: workflow_dispatch

jobs:
  replace-secrets:
    name: Deleted file recovering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Recover + content show
        shell: bash
        run: |
          set -x
          filesha=$(git log -n 1 --pretty=format:%H -- lala1.yaml)
          git checkout "$filesha"^ -- lala1.yaml
          cat lala1.yaml
