name: Deploy CI

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
        
      - name: Detect changes
        run: |
          # Obtén la lista de archivos cambiados
          changed_files=$(git diff --name-only HEAD~1..HEAD)
          changedValues=$(echo $changed_files | grep "values.yaml"
          echo $changedValues

          if echo "$changedValues"; then
            echo "El archivo que ha cambiado es $changedValues: 
          else
            echo "Ningún archivo de values.yaml ha cambiado"
          fi



      - name: testing
        run: |
           echo "Before: ${{ github.event.before }}"
           echo "SHA: ${{ github.sha }}"
           changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
           echo "Changed files: $changed_files"
           if [[ -n "$changed_files" ]]; then
             echo "::set-output name=values-changed::true"
           else
             echo "::set-output name=values-changed::false"
           fi

           
