name: Deploy CI

on:
  workflow_dispatch:


jobs:

  deploy:
        name: Deploy
        uses: stemdo/workflows/.github/workflows/helm-v1.yml@main
        with:
          helm_version: 'v3.10.1'
        #   helm_namespace: 'cert-manager'   Usar siempre namespaceOverride y agregar el namespace
          helm_chart: 'charts/godaddy-webhook'