name: Deploy CI

on:
  push:

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
        
      - name: Detect changes
        run: |
          # Obtén la lista de archivos cambiados
          changed_files=$(git diff --name-only HEAD~1..HEAD)

          echo $changed_files
          # Verifica si un archivo específico ha cambiado
          if echo "$changed_files" | grep -q "values.yaml"; then
            echo "El archivo 'apps/pro/k8s/values.yaml' ha cambiado"
          else
            echo "El archivo 'apps/pro/k8s/values.yaml' no ha cambiado"
          fi



      - name: testing
        run: |
           echo "Before: ${{ github.event.before }}"
           echo "SHA: ${{ github.sha }}"
           changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
           echo "Changed files: $changed_files"
           if [[ -n "$changed_files" ]]; then
             echo "::set-output name=values-changed::true"
           else
             echo "::set-output name=values-changed::false"
           fi

           
