name: Replace Secrets

on: workflow_dispatch

jobs:
  replace-secrets:
    name: Reemplazar Secretos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get secret names
        run: |

          secret_names=""
          line=$(grep "secrets_replacement:" ".github/workflows/var_replacement.yml")
          if [[ $line == *"secrets."* ]]; then
            line_secrets=$(echo $line | grep -oP '(?<=secrets\.)\w+')
            for secret in $line_secrets; do
              secret_names+="$secret "
            done
          fi
          echo "SECRET_NAMES=${secret_names% }" >> $GITHUB_ENV

      - name: Run Secret Replacement Script
        run: ./var_replacement.sh
        shell: bash
        env:
          filenames: "apps/pro/k8s/asd.yaml apps/pro/k8s/configmap.yaml apps/pro/k8s/asding.yaml"
          secrets_replacement: "${{ secrets.GRAFANA_INI_DBHOST }} ${{ secrets.GRAFANA_INI_DBPASSWORD }} ${{ secrets.GRAFANA_INI_DBUSER }} ${{ secrets.GRAFANA_INI_SMTPFROMADDRESS }} ${{ secrets.GRAFANA_INI_SMTPHOST }} ${{ secrets.TEST }} ${{ secrets.ASD }}"
          secrets_names: "${{ env.SECRET_NAMES }}"

