name: Replace Secrets

on: [push, pull_request, workflow_dispatch]

jobs:
  replace-secrets:
    name: Reemplazar Secretos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          # Aquí puedes configurar cualquier otra cosa necesaria para tu script

      - name: Run Secret Replacement Script
        run: var_replacement.sh
        env:
          filename: "test.yaml configmap.yaml testing.yaml"
          secrets: "${{ secrets.GRAFANA_INI_DBHOST }} ${{ secrets.GRAFANA_INI_DBPASSWORD }} ${{ secrets.GRAFANA_INI_DBUSER }} ${{ secrets.GRAFANA_INI_SMTPFROMADDRESS }} ${{ secrets.GRAFANA_INI_SMTPHOST }} ${{ secrets.TEST }} ${{ secrets.ASD }}"
